# Generated by Django 4.0.1 on 2022-01-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='prize_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.prize'),
        ),
    ]
