# Generated by Django 4.0.1 on 2022-01-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_winner_prize_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='prize_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.prize'),
        ),
    ]
