# Generated by Django 4.0.1 on 2022-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_winner_prize_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='winner',
            name='prize_id',
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
