# Generated by Django 4.0.1 on 2022-01-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_genre_remove_winner_prize_id_delete_prize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=30)),
                ('genre', models.ManyToManyField(to='music.Genre')),
            ],
        ),
    ]
