# Generated by Django 4.0.1 on 2022-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_singer_song_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
