# Generated by Django 4.0.1 on 2022-01-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singer',
            new_name='singers',
        ),
    ]
