# Generated by Django 4.0.1 on 2022-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_rename_singer_song_singers'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
