# Generated by Django 4.0.1 on 2022-01-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_song_lyrics_alter_song_description_alter_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('song', models.ManyToManyField(to='music.Song')),
            ],
        ),
    ]
