# Generated by Django 4.0.1 on 2022-01-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_area_language_type_singer_area_singer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
