# Generated by Django 4.0.1 on 2022-01-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_genre_genre_alter_language_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url',
            new_name='website',
        ),
    ]
