# Generated by Django 4.0.1 on 2022-01-09 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_song_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
