# Generated by Django 4.0.1 on 2022-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_song_image_song_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='times_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='times_play',
            field=models.IntegerField(default=0),
        ),
    ]
