# Generated by Django 4.0.1 on 2022-01-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_playlist_times_play_song_times_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.CharField(default='lyricSong.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(default='aimer.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.CharField(default='audio.mp3', max_length=100),
        ),
    ]
