# Generated by Django 4.0.1 on 2022-01-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_playlist_image_alter_song_image_alter_song_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='singers',
            new_name='singer',
        ),
    ]
